### ISSUE TITLE
Customize the priority of a rule

### ISSUE THREAD

**Issue by dparne** [oclint/oclint#131]
Is it possible to pass in some argument to the oclint command to change the priority of a rule? I looked around the documentation, It seems we can change the threshold of a rule but could not find anything for changing priority.

Thanks,
Dinesh

**Comment by socoboy** [comment]
Hi there, could anyone implement this enhancement :). I really want to be able to customize a rule priority just like how we deal with threshold

Thanks

**Comment by UnrealQuester** [comment]
@socoboy do you have any rules you want to change specifically because you think they have an unreasonable priority?

If you want to be able to change the prioroity of rules in general you currently have to change the priority in the source and recompile these rules. As you can tell oclint where to look for the rules, you could in theory have multiple rule folders each with different priorities.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
