### ISSUE TITLE
No way to tell clang to use custom analyzer checkers

### ISSUE THREAD

**Issue by mikemccracken** [oclint/oclint#145]
From what I can tell, the only way to tell the clang analyzer to use non-default checkers, such as the alpha.cplusplus checkers, is to pass them on the command line to clang. 

It'd be nice if there was a way to specify which checkers to run.
Alternatively, a way to pass arbitrary flags through to the analyzer would also be useful.

**Comment by adudurant** [comment]
The issue is great

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
