### ISSUE TITLE
Macro Visitor

### ISSUE THREAD

**Issue by jpsim** [oclint/oclint#148]
I'm in the early stages of working on a rule to detect if a localized string is missing its entry in the `Localizable.strings` file.

Is there a clang visitor I can use to only visit macros with a certain name? In this case, `NSLocalizedString()`.

Right now, my rule visits the expanded version of the macro, but that only works when explicitly writing the expansion: `[[NSBundle mainBundle] localizedStringForKey:@"key" value:nil table:nil]`.

You can see my rule in progress [here](https://github.com/jpsim/oclint/blob/MissingLocalizedStringRule/oclint-rules/rules/cocoa/MissingLocalizedStringRule.cpp).

Thanks!

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
