### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by happenroc** [oclint/oclint#224]
In the middle of analysis, the process dropped and shows:

Assertion failed: (getObjCLifetime() == qs.getObjCLifetime() || !hasObjCLifetime() || !qs.hasObjCLifetime()), function addConsistentQualifiers, file /Users/lqi/Jenkins/oclint/workspace/oclint-ci/oclint-build-nodes/master/oclint/llvm/tools/clang/include/clang/AST/Type.h, line 399.

After exclude the related file by "-e" parameters, the analysis can finish and generate report normally. 
When I started a single file analysis on that file, the same error message was logged.

Environment: OS X 10.9.5 + Xcode 6.0.1 + OCLint 0.9

**Comment by chichimei** [comment]
Is there any solution for this problem?

**Comment by nishantmr** [comment]
was a solution on this found?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
