### ISSUE TITLE
'ivar assignment outside accessors or init' even if no property available?

### ISSUE THREAD

**Issue by michaelochs** [oclint/oclint#228]
I see the warning that I assign or access iVars, even though the iVar in question does not have a property. Is this intended and can this be switched off? I think the use of an ivar over a property is an issue, but there might be cases where one explicitly does not want to have a property available for certain structs or states. In this case the warning is quite useless as there is no other way to access the content of the iVar...

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
