### ISSUE TITLE
Open mind to Write some custom rules

### ISSUE THREAD

**Issue by GeekMin** [oclint/oclint#237]
// if g() is not the last sentence in method f(), warning given
int f(){
  g();  // warning here
  xxx;
}

I wanna define a checker to find this problem
1. firstly, I think I can use "Source Code Reader Rules" to do this, because I think I can store the status of pre-get line-text: if g() next line is not '}'(maybe regex here) I will give the warning.. Is this OK?
2. think again: I wanna use ASTMatcher: but how can I know the method_call's relative position in f()
3. think twice: I wanna use visitor pattern, the detail now i do not have a clue~
I just touch OClint, AST; but for me, I wanna collect some thoughts about the custom checker...&& different patterns, different abilities..  
AST Visitor + Source Code Reader Rules + ASTMatcher...any places have more examples...? that I think I can earn time[one document here~~ forgive me so many requests... 

PS: now i wanna scan the objective-c project..

Best Regards

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
