### ISSUE TITLE
Additional rules request

### ISSUE THREAD

**Issue by technion** [oclint/oclint#238]
Hi,

Many thanks for this project. I've been using splint for years but swapping out with oclint has been a significant improvement.

I've got two splint reports on a codebase that oclint considers clean. I was wondering if it would be possible to write rules for these scenarios? 

simulator.c:48:2: Return value (type int) ignored: system(readline)
  Result returned by function call is not used. If this is intended, can cast
  result to (void) to eliminate message. (Use -retvalint to inhibit warning)
simulator.c:10:5: Function exported but not used outside simulator: runloop
  A declaration is exported, but not used outside this module. Declaration can
  use static qualifier. (Use -exportlocal to inhibit warning)
   simulator.c:52:1: Definition of runloop

The first in particular is, imo, quite a relevant, rule - the return value of system() should usually be checked.

I haven't included source because it's fairly obvious what these alerts are telling me and complaining about, but please let me know if I can provide further information.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
