### ISSUE TITLE
cmake support to be able to write own rules (private)

### ISSUE THREAD

**Issue by arnaudgelas** [oclint/oclint#303]
In long term, it would be great to be able to write own rules with code and couple of cmake lines.

Note that I have started working on dependency, install, export mechanism here:

 https://github.com/arnaudgelas/oclint/commit/1cd67fff94b5cac955b260790416030bb0f7f0ab

I don't have much time these days, but any comments, help would be highly appreciated!

Note: it should be fairly easy to use external project mechanism in your own project (with the current status)

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
