### ISSUE TITLE
Add Rule to Check Header for having Nullability Annotations

### ISSUE THREAD

**Issue by fabb** [oclint/oclint#324]
This one is helpful for mixed ObjC/Swift projects. Missing nullability annotations result in parameters and return values being implicitly unwrapped by default, which can lead to crashes.

A new rule that checks if all pointers are annotated with nullability would be awesome.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by fabb** [comment]
This has not yet been implemented as far as I can tell, and it is still something desirable.

**Comment by ryuichis** [comment]
Your point is valid, but we currently skip checking headers to avoid high false positives and performance issues. Help is needed to figure that out prior to this.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
