### ISSUE TITLE
Allow a way to give an output folder to -enable-clang-static-analyzer

### ISSUE THREAD

**Issue by BobatBH** [oclint/oclint#330]
The clang docs for scan-build say that the html (or plist) files are placed in /tmp if the -o option isn't used. Apparently oclint IS supplying this option as the plist files are dumped in the current directory. I'd like a way to specify where they're placed so I can clean up and, more importantly, set up an entry in my .gitignore.

Thanks for your consideration!

**Comment by vinyldarkscratch** [comment]
Hey there, I feel the same way myself, and am currently working on it, narrowing it down to the core.  Looks like Clang just dumps .plist files into the current working directory, which is programmatically set to the project folder (-p /path/to/project/ or current dir).  Creating a new folder and setting that as the cwd should do the trick, or another trick might reveal itself, hopefully!

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
