### ISSUE TITLE
Blocks assigned to variables should not be checked with LongVariableName

### ISSUE THREAD

**Issue by BobatBH** [oclint/oclint#331]
```
NSArray* myArray = @[];
NSString* (^someReallyLongBlockNameThatIsCalledLikeAMethod)(NSArray*) = ^(NSArray* whatever)
{
    NSLog(@"%@", whatever);
    return whatever.description;
};

NSString* myString = someReallyLongBlockNameThatIsCalledLikeAMethod(myArray);
```

In my opinion, they should be considered as method names instead.

My suggestion is to either do as the issue subject describes, or create a new LongMethodName rule and apply that to blocks.

Thanks for your consideration.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
