### ISSUE TITLE
Generating multiple reports request

### ISSUE THREAD

**Issue by authorfeng** [oclint/oclint#362]
http://docs.oclint.org/en/stable/howto/selectreporters.html
Hello, can you please tell me if oclint support generating multiple reports at one analyze? 
If not, can you please support it?

**Comment by UnrealQuester** [comment]
Multiple reporters are not supported in one invocation. You have to call oclint multiple times.
May I ask what your use case is for needing multiple reporters?

**Comment by authorfeng** [comment]
@UnrealQuester We need html report for human reading, and json or xml report for program analysis, but call oclint multiple times for different reports is worse of time. Maybe we can parse html, but it is best if you can support multiple reporters in one invocation.

**Comment by ryuichis** [comment]
Instead of parsing html, the real-world example we have is to generate the json report, and then reformat that for any structures you want. We did some experiments like https://github.com/oclint/oclint-codeclimate/blob/master/oclint-codeclimate#L61

**Comment by michaeleisel** [comment]
@ryuichis the issue is that none of the machine-friendly formats show whether or not an error has occurred. the only formats that seem to do it are html and text. so if we want to parse the output and also know if one or more errors has occurred, it either requires a lot of munging of report formats that seem likely to change between versions, or doing multiple oclint calls
