### ISSUE TITLE
"1 Error generated" on one of my two machines

### ISSUE THREAD

**Issue by bart-kneepkens** [oclint/oclint#422]
### Issue Summary
OCLint prints '1 error generated' quite some times, making the output file incomplete. This issue only happens on one of my two machines, which have the same version of MacOS, Xcode, OCLint and OCLint dependencies installed.

### Environment
- Operation system name and version: MacOS Sierra 10.12.4
- OCLint version: 0.12 (although same issue for 0.11 and 0.11.1)
- Xcode version: 8.3
- How OCLint is installed: homebrew install

### Commands
    xcodebuild -workspace {workspace} -scheme {scheme} | tee myLog.log
    oclint-xcodebuild myLog.log

or

    xcodebuild -workspace {workspace} -scheme {scheme} | xcpretty --report json-compilation-database --output compile_commands.json

then

    oclint-json-compilation-database {options}

### Expected Behavior
I expect both machines to behave the same. That is, lint silently except for listing the rules.

### Actual Behavior
Only one of the machines behaves as expected. On the other machine, I get an output listing the rules, and then repeatedly saying `1 error generated` but nothing more.

How can I fix this issue?

- macOS version is the same
- OCLint version is the same
- Xcode version is the same
- dependencies version are the same and same path

**Comment by bart-kneepkens** [comment]
Seems to be related to #302

**Comment by ryuichis** [comment]
@bart-kneepkens for the machine that you see this error, could you delete the current `compile_commands.json` file, run `xcodebuild clean -workspace {workspace} -scheme {scheme}`,  maybe delete the project intermediate files from `DerivedData` folder. So the goal is to give your project a clean stage, and then run oclint again.

I am closing this, and hope the conversation would continue in #302. I have been informed with this type of error once in a while, but I never see it myself, and so far, nobody shares any sample projects that allow me to replicate the same thing locally. Let me know if you could tell the difference between your two machines, so that I can take a deep look.
