### ISSUE TITLE
Is there any way to get a JSON report but also know of compiler errors?

### ISSUE THREAD

**Issue by michaeleiselsc** [oclint/oclint#434]
### Issue Summary
Short of writing my own reporter, is there any way to get OCLint output in an organized format like JSON or XML but with the compiler errors reported in some way? Even just knowing whether or not 1 or more compiler errors have occurred would do the job, so that I know that the results are valid or require further investigation. For example, reporting the same results out to two reporters, a plain text to check for the error string and a JSON to do the real parsing, would do the job.

**Comment by adudurant** [comment]
No compiling successfully no analyzing

**Comment by michaeleiselsc** [comment]
Right, but even if compilation fails, it's able to output a result saying that compilation failed. It's just that certain formats don't include compilation failures

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
