### ISSUE TITLE
oclint-json-compilation-database报错

### ISSUE THREAD

**Issue by slzhou** [oclint/oclint#503]
执行oclint-json-compilation-database -e Pods oclint_args  -- -rc=LONG_LINE=200 -rc=NCSS_METHOD=100  -o=report.html报错：
Skipping /WorkSpace/OCLint/SuperLogger/SuperLoggerDemo/oclint_args. Compile command not found.
report.html里的内容：
OCLint Report Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0 [OCLint (http://oclint.org) v0.13]
这不对啊，一个警告都没有检查出来，oclint_args是个什么东西啊？为啥当做文件跳过啊？

**Comment by fusunlang** [comment]
请问这个问题解决了么？

**Comment by JungHsu** [comment]
Xcode中需要单独设置环境变量，哪怕你已经在电脑的配置文件下配置了OCLint的环境变量

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by Zhangyanshen** [comment]
去掉oclint_args，这个是提示你后面可以添加oclint的参数，不是一个真正的参数

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
