### ISSUE TITLE
oclint error

### ISSUE THREAD

**Issue by shengwanlin** [oclint/oclint#515]
### Issue Summary
use oclint-json-compilation-database command I get a error : 

```
oclint: error: cannot open report output file /Users/sunvlink/Desktop/publicHealthOnline/PublicHealthOnline/oclint_result.html
```

**Comment by AugustRush** [comment]
+1

**Comment by xiaodingdang18** [comment]
+1，  oclint :error cannot open report output file 
 LLVM version 5.0.1
  Optimized build.
  Default target: x86_64-apple-darwin17.7.0
  Host CPU: broadwell
OCLint (http://oclint.org/):
  OCLint version 0.13.1.
  Built Feb  6 2018 (09:25:36).

**Comment by ShenYj** [comment]
+1111111

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
