### ISSUE TITLE
Ways to tell from arc or mrc. 

### ISSUE THREAD

**Issue by carusd** [oclint/oclint#527]
I'm maintaining a really old project, which is mixing with arc and mrc.  And I want to write some new rule to check some code, with different coding should comes with different checking solutions. Is there a way know whether this file is using automatic reference counting or manual reference counting in the rule class ?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
