### ISSUE TITLE
homebrew cask needs updated to 0.15

### ISSUE THREAD

**Issue by stonedauwg** [oclint/oclint#542]
### Issue Summary
Homebrew cask formulae has not been updated for the latest 0.14 release. Still set to last version of 0.13.1

### Environment
- macos mojave 10.14.5
- homebrew install

**Comment by kcharliek** [comment]
please!!!

**Comment by illbebach** [comment]
bump

**Comment by lk220203006** [comment]
please!!!

install by the code ,always stop in this step

dev@DevdeMac-mini oclint-scripts % ./make
Cloning into 'oclint-json-compilation-database'...
remote: Enumerating objects: 88, done.
remote: Total 88 (delta 0), reused 0 (delta 0), pack-reused 88
Unpacking objects: 100% (88/88), done.
Cloning into 'oclint-xcodebuild'...
remote: Enumerating objects: 85, done.
remote: Total 85 (delta 0), reused 0 (delta 0), pack-reused 85
Unpacking objects: 100% (85/85), done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   670  100   670    0     0    558      0  0:00:01  0:00:01 --:--:--   557
  1  424M    1 7513k    0     0  40690      0  3:02:11  0:03:09  2:59:02 11515

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichis** [comment]
This pull request https://github.com/oclint/homebrew-formulae/pull/6 should addressed this issue.
