### ISSUE TITLE
Photos.framework warning in Xcode 11.3

### ISSUE THREAD

**Issue by YanxiFeng** [oclint/oclint#556]
oclint warning:
Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Photos.framework/Headers
--
When i update my Xcode to 11.3, every time i run code check, it will show these warnings.
PHError.h:10, compiler error, Priority: High
expected '('.
PHError.h:10, compiler error, Priority: High
'#pragma clang attribute pop' with no matching '#pragma clang attribute push'.
...
But i can't see in Xcode directly.

**Comment by lpfRoc** [comment]
me too

**Comment by MagLiC** [comment]
Is there a solution？

**Comment by lk220203006** [comment]
me too
oclint version is 0.13

**Comment by ShenYj** [comment]
me 吐

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
