### ISSUE TITLE
OCLint takes a long time to finish

### ISSUE THREAD

**Issue by buptwsg** [oclint/oclint#574]
Issue Summary

Environment

Operation system name and version: Mac OS 10.14.5
OCLint version: 0.13.1
How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
local build
Reproduction Steps

Detailed steps to reproduce the issue.

Sample code

C
C++
Objective-C
Command to run OCLint with the code above:

xcodebuild clean -scheme iOSTests -workspace iOSTests.xcworkspace -sdk iphonesimulator && xcodebuild build COMPILER_INDEX_STORE_ENABLE=NO -scheme iOSTests -workspace iOSTests.xcworkspace -sdk iphonesimulator -dry-run -UseNewBuildSystem=NO | xcpretty -r json-compilation-database --output compile_commands.json

oclint-json-compilation-database -v -e Pods -- -report-type html -o oclintReport.html

Expected Behavior

oclint-json-compilation-database should finish in a short time for a simple test iOS project.

Actual Behavior

The command takes a long time to finish, I noticed that oclintReport.html is generated very quickly, but the command doesn't finish after the report is generated.

Even Better

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
