### ISSUE TITLE
Homebrew formulae is out of date, should be version 0.15

### ISSUE THREAD

**Issue by claybridges** [oclint/oclint#577]
### Issue Summary
Homebrew formulae is out of date, should be version 0.15.

Not sure of best way to address this other than posting an issue here. I've been trying my hand at updating it, but it's non-trivial.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by claybridges** [comment]
This is still a problem.

**Comment by ryuichis** [comment]
I recently merged a pull request https://github.com/oclint/homebrew-formulae/pull/6, does that address your issue @claybridges ?

**Comment by claybridges** [comment]
> does that address your issue @claybridges ?

*YES!*
```
==> Upgrading 1 outdated package:
oclint/formulae/oclint 0.13 -> 20.11
==> Upgrading oclint/formulae/oclint 0.13 -> 20.11 
```
