### ISSUE TITLE
OCLint hasn't had a binary release since 0.13.1 (2 years)

### ISSUE THREAD

**Issue by TomMD** [oclint/oclint#580]
### Issue Summary
As a user of oclint, I'd like to install it on my CI systems with ease.  Sadly, OCLint isn't in the apt package set nor does it have a binary included with the release (contrary to claims in the installation page).

### Environment
- Operation system name and version: Ubuntu 20.04 x86_64
- OCLint version: 20.10
- How OCLint is installed: Well I'd like "prebuilt binary downloaded from github?" but don't see one.  Am I missing it?

**Comment by ryuichis** [comment]
Hi @TomMD I wish I had the time to do a better job updating the document, but I prefer people build their local version these days to avoid unnecessary incompatibility issue, especially on the macOS side. With that said, I am adding aarch64 support in the coming release, and building the required LLVM dependencies and OCLint itself on aarch64 takes a good amount of time, so I am currently thinking to again provide prebuilt binaries just so that it can save everybody's time. I will update this issue again when that happens.

**Comment by ryuichis** [comment]
I am closing this one as the prebuilt binaries are available for release 20.11.
