### ISSUE TITLE
one bug about "useless parentheses"

### ISSUE THREAD

**Issue by Junerescue67** [oclint/oclint#582]
==================
#include<stdio.h>
int main()
{
    unsigned x, p, n;
    scanf_s("%u %u %u", &x, &p, &n);
    unsigned tool;
    unsigned max1 = UINT_MAX;
    unsigned max2 = UINT_MAX;
    max1 <<= p - n + 1;
    max2 >>= 31 - p;
    tool = max1 & max2;
    x &= tool;
    x >>= p - n + 1;
    printf("%u", x);
    return 0;
}
===================
上面是我的测试代码，oclint会报一个 “useless parentheses”的错误。错误位置在
  unsigned max1 = UINT_MAX;
  unsigned max2 = UINT_MAX;
中的“U"这个字母的位置。
我觉得是oclint的判断机制的问题。

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichis** [comment]
Duplication #378
