### ISSUE TITLE
Unable to install/use oclint with a Dockerfile based on alpine-linux

### ISSUE THREAD

**Issue by nvuillam** [oclint/oclint#584]
### Issue Summary
In order to add oclint to [Mega-Linter](https://github.com/nvuillam/mega-linter#readme), I have an issue to install/use oclint on docker alpine image

```dockerfile
FROM python:alpine
.....
RUN apk add rpm ncurses5 ncurses5-libs
RUN wget https://github.com/oclint/oclint/releases/download/v0.13.1/oclint-0.13.1-x86_64-linux-4.4.0-112-generic.tar.gz \
              && mkdir oclint-release \
              && tar xf oclint-0.13.1-x86_64-linux-4.4.0-112-generic.tar.gz -C oclint-release --strip-components 1 \
              && chmod +x /oclint-release/bin/oclint
ENV OCLINT_HOME /oclint-release
ENV PATH $OCLINT_HOME/bin:$PATH
RUN echo 'PATH=$OCLINT_HOME/bin:$PATH' >> ~/.bashrc
```

Result  of `oclint -version` called inside the container:
```
oclint -version
127 oclint: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

Development branch: https://github.com/nvuillam/mega-linter/blob/oclint/Dockerfile

I tried to find on google & github, impossible to find a dockerfile with oclint installed from a linux alpine image (they are all using ubuntu) , have you ever heard of an alpine-linux working example ?

**Comment by ryuichis** [comment]
Thank you @nvuillam for the interests of the tool. There are a few issues here:

1. LLVM community provides official prebuilt binaries for Ubuntu, and that's what OCLint uses by default. I am not aware of an official binary for Alpine, but there might be community build that you can consider to use. If you are still out of luck there, you may have to consider building your own LLVM/Clang toolchain and OCLint in order to be platform compatible. Or perhaps altering the LD_LIBRARY_PATH to find the correct dependent libraries.

2. 0.13 is a fairly old OCLint version, you may consider upgrade it to 20.10. I understand I don't provide prebuilt binaries any more, but considering the first point above, you may want to do it anyway.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
