### ISSUE TITLE
Build from source fails on Debian 10 and RHEL8

### ISSUE THREAD

**Issue by bracketttc** [oclint/oclint#600]
### Issue Summary
On Debian 10 and RHEL8, using GNU C/C++ Compiler 8.3.1, the build from source fails with undefined symbols in pre-compiled LLVM static libraries.

### Environment
- Operation system name and version: Debian 10, RHEL8
- OCLint version: 20.11
- How OCLint is installed: local build

### Reproduction Steps
Using a Debian10 or RHEL8 system, clone the git repository and run `./make` from the `oclint-scripts` directory.

### Expected Behavior
Expect to get a statically-linked `oclint` binary.

### Actual Behavior
Failure to link `oclint` citing a number of undefined symbols in various `.a` files under `build/llvm-install`.

**Comment by ryuichis** [comment]
`./make` uses the official LLVM/Clang release binaries provided by LLVM community, and for Linux, that defaults to Ubuntu. You can build LLVM binaries locally, and then use `makeWithSystemLLVM` script instead by specifying the path to the LLVM installation.

Let me know how it goes.

**Comment by bracketttc** [comment]
What version of LLVM is required?

Would you be open to a PR that uses CMake ExternalProject to get the source if required?

**Comment by ryuichis** [comment]
The latest release 20.11 uses LLVM 11.0.0, but I expect 11.0.1 would also work.

I would be interested to see how this is done using CMake ExternalProject. We need to copy certain LLVM/Clang headers to the release bundle, which may require changes to the python scripts though.

**Comment by bracketttc** [comment]
Can confirm that 11.0.1 works. LLVM only claims that the API is stable over
a minor version, so that’s expected.

I’ll see what I can do about getting CMake to handle fetching and building
the appropriate pieces of LLVM.

**Comment by kardashe** [comment]
while I do like oclint , this version is just over the board with how much time has to be wasted on building.... 

same thing happened to me, tried the suggested, wasted lots of time to no avail....


1. CommonOptionsParser optionsParser(argc, argv, OCLintOptionCategory);  // it is now protected in llvm 11.0.1 and does not compile, so I made it public just for the hack of it, and recompiled llvm and clang, and oclint with it AND... holding my breath ...
2. program aborted due to an unhandled Error:
Error value was Success. (Note: Success values must still be checked prior to being destroyed).

Program received signal SIGABRT, Aborted.
0x00007ffff67bc387 in raise () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-36.el7_6.2.x86_64 libstdc++-4.8.5-36.el7_6.2.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) where
#0  0x00007ffff67bc387 in raise () from /usr/lib64/libc.so.6
#1  0x00007ffff67bda78 in abort () from /usr/lib64/libc.so.6
#2  0x0000000003d5965f in llvm::Error::fatalUncheckedError (this=0x7fffffffc978) at /export/home/kardashe/llvm-project/llvm/lib/Support/Error.cpp:112
#3  0x0000000001163cb8 in oclint::CompilerInstance::start() ()
#4  0x00000000011532ea in invoke(std::vector<std::pair<std::string, clang::tooling::CompileCommand>, std::allocator<std::pair<std::string, clang::tooling::CompileCommand> > >&, std::string&, oclint::Analyzer&) ()
#5  0x00000000011540dd in oclint::Driver::run(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::string>, oclint::Analyzer&) ()
#6  0x000000000114e369 in main ()
(gdb)

I think it is ridiculous, that the build depends on whether somebody somewhere supports Ubuntu only... 

waiting for another year or so to see if things normalize....

**Comment by ryuichis** [comment]
@bracketttc Thanks for the confirmation. Look forward to a pull request from you if you manage to get the CMake pieces working.
