### ISSUE TITLE
undefined reference to std::_Sp_make_shared_tag::_S_eq(std::type_info const&)

### ISSUE THREAD

**Issue by samcramer** [oclint/oclint#634]
### Issue Summary
When trying to make oclint on Ubuntu 18.04, I get the following error when linking oclint:

`/home/scramer/src/oclint/build/llvm-install/lib/libclangStaticAnalyzerCheckers.a(CloneChecker.cpp.o): In function std::_Sp_counted_ptr_inplace<llvm::Regex, std::allocator<llvm::Regex>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)':
CloneChecker.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceIN4llvm5RegexESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info[_ZNSt23_Sp_counted_ptr_inplaceIN4llvm5RegexESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info]+0x11): undefined reference to 'std::_Sp_make_shared_tag::_S_eq(std::type_info const&)'`

### Environment
- Operation system name and version: Ubuntu 18.04.06 LTS
- OCLint version: v22.02
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
-- local build

### Reproduction Steps
Versions of tools:
- ninja version 1.8.2
- cmake version 3.16.3
- gcc version 7.5.0

#### Sample code

Not applicable.

### Expected Behavior
Successful build of oclint.

### Actual Behavior
ld error due to undefined reference:

`/home/scramer/src/oclint/build/llvm-install/lib/libclangStaticAnalyzerCheckers.a(CloneChecker.cpp.o): In function std::_Sp_counted_ptr_inplace<llvm::Regex, std::allocator<llvm::Regex>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)':
CloneChecker.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceIN4llvm5RegexESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info[_ZNSt23_Sp_counted_ptr_inplaceIN4llvm5RegexESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info]+0x11): undefined reference to 'std::_Sp_make_shared_tag::_S_eq(std::type_info const&)'`

### Even Better

Not applicable.

**Comment by ryuichis** [comment]
The reference comes from libClang. How you locally built the libClang?

**Comment by samcramer** [comment]
Thanks for the reply.

I didn't build libClang.  I used the Ubuntu 18.04 packages: libclang-common-10-dev, libclang-common-9-dev, libclang-cpp10, libclang-cpp9, libclang1-10 and libclang1-9.  Since I now know that the problem is with libclang I see if I'm pointing to the right version or if I need to build it mayself.

**Comment by tygokf** [comment]
When building OClint with [make](https://github.com/oclint/oclint/blob/master/oclint-scripts/make) a prebuilt binary for clang and llvm is used, however this binary is meant for Ubuntu 20.04. 

A solution to this problem is to use [makeWithSystemLLVM](https://github.com/oclint/oclint/blob/master/oclint-scripts/makeWithSystemLLVM) and add as argument the absolute path to the prebuilt binary that is meant for Ubuntu 18.04. You can get this binary from https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
