### ISSUE TITLE
OClint on windows 10

### ISSUE THREAD

**Issue by chapa17** [oclint/oclint#647]
### Issue Summary
Trying to run OClint on Windows 10

### Environment
- Operation system name and version: Windows 10
- OCLint version: 22.02
- How OCLint is installed: local build on Ubuntu 22 using Virtualbox

### Reproduction Steps
I installed OClint on Ubuntu Virtualbox present in Windows OS. I was able to run the sample code on Ubuntu however my code and code executables everything lies on Windows system. I tried using shared folder but it still has the file paths as my Windows system. 

I also thought of using a cross-compiler to generate binaries and executables suitable for Ubuntu however even that does not resolve this.

I would like to know if there are any other ideas to run OClint on the Windows executable files.

Thank you in advance!

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
