### ISSUE TITLE
Xcode14.3，OCLint: 20.11 oclint: error: compilation contains multiple jobs: 

### ISSUE THREAD

**Issue by tenxun123** [oclint/oclint#651]
### Issue Summary
oclint: error: compilation contains multiple jobs:

### Environment
- Operation system name and version: Mac OS：13.3 (22E252)， Xcode 14.3
- OCLint version:   /bin/oclint-20.11
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?

### Reproduction Steps
Running OCLint.....
oclint: error: compilation contains multiple jobs:
 "/usr/local/Cellar/oclint/20.11/bin/oclint-20.11" "-cc1" "-triple" "arm64-apple-ios11.0.0" "-Wundef-prefix=TARGET_OS_" "-Werror=undef-prefix" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-Werror=implicit-function-declaration" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "iphoneos16.4-20E238-.sdkstatcache" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=non-leaf" "-fno-rounding-math" "-munwind-tables" "-target-sdk-version=16.4" "-fcompatibility-qualified-id-

#### Sample code

```
C
C++
Objective-C
```

**Comment by luqiuan** [comment]
> 兄弟，问题有解决吗

 兄弟，问题有解决吗?

**Comment by michaelrourke** [comment]
Comparing Xcode 14.2 vs Xcode 14.3 oclint-json-compilation-database output yields some differences.
In my case, Xcode 14.3 sometimes issues an extra argument over XCode 14.2:
-ivfsstatcache XXXXXXX.sdkstatcache

Using sed to strip this out of the xcpretty json output before feeding to oclint-json-compilation-database resolves the issue.

sed 's/-ivfsstatcache [^ ]*//g' < compile_commands.json > icompile_commands.json
mv icompile_commands.json compile_commands.json

**Comment by Vincentzzg** [comment]
> Comparing Xcode 14.2 vs Xcode 14.3 oclint-json-compilation-database output yields some differences. In my case, Xcode 14.3 sometimes issues an extra argument over XCode 14.2: -ivfsstatcache XXXXXXX.sdkstatcache
> 
> Using sed to strip this out of the xcpretty json output before feeding to oclint-json-compilation-database resolves the issue.
> 
> sed 's/-ivfsstatcache [^ ]*//g' < compile_commands.json > icompile_commands.json mv icompile_commands.json compile_commands.json

xcode14.2 is OK?

**Comment by michaelrourke** [comment]
Yes Xcode14.2 is ok. With OCLint version 23.0. At least for my simple app.

**Comment by Vincentzzg** [comment]
> Yes Xcode14.2 is ok. With OCLint version 23.0. At least for my simple app.

I will try Xcode14.2。But the lastest version of OCLint is 22.02.

**Comment by Vincentzzg** [comment]
<img width="718" alt="image" src="https://github.com/oclint/oclint/assets/10241716/2fcc4382-2474-47eb-9584-7f1dd9cf6eb6">

**Comment by michaelrourke** [comment]
Sorry for the confusion. With the move to Apple silicon I followed the recommendations in the issue titled [Please upgrade oclint to llvm14.0](https://github.com/oclint/oclint/issues/651#top) so built from this source: https://github.com/Lianghuajian/oclint/tree/support_xcode14

**Comment by Vincentzzg** [comment]
ok，I will try this version with Xcode14.2

**Comment by Vincentzzg** [comment]
> Comparing Xcode 14.2 vs Xcode 14.3 oclint-json-compilation-database output yields some differences. In my case, Xcode 14.3 sometimes issues an extra argument over XCode 14.2: -ivfsstatcache XXXXXXX.sdkstatcache
> 
> Using sed to strip this out of the xcpretty json output before feeding to oclint-json-compilation-database resolves the issue.
> 
> sed 's/-ivfsstatcache [^ ]*//g' < compile_commands.json > icompile_commands.json mv icompile_commands.json compile_commands.json

Is this solution with OCLint version 23.0?

**Comment by michaelrourke** [comment]
yes. this works with the so called  OCLint version 23.0 (which isn't an official release but from [lianghuajian](https://github.com/Lianghuajian))

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by manuelzi** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

Ok, I was using version 22.02 when I experienced this issue.

**Comment by Vincentzzg** [comment]
大家问题有解决吗？我一直在等OCLint的新版本修复这个问题，项目的静态扫描已经停了几个月了

**Comment by FirstDKS521** [comment]
xcode 15, oclint 22.02，解析compile_commands.json时报错，oclint: error: compilation contains multiple jobs:  怎么处理

**Comment by CodeSnowMonkey** [comment]
xcode 15.1, oclint 22.02，解析compile_commands.json时报错，oclint: error: compilation contains multiple jobs: 怎么处理

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by Coder-Star** [comment]
> xcode 15.1, oclint 22.02，解析compile_commands.json时报错，oclint: error: compilation contains multiple jobs: 怎么处理

这个有解决吗

**Comment by shunsongshiyi** [comment]
![image](https://github.com/oclint/oclint/assets/68367949/90d9ca6d-04bf-47c8-83c4-658b401cf0f5)
My same issue`oclint: error: compilation contains multiple jobs` fixed by remove `-ivfsstatcache /Users/mrzhao/derivedData/SDKStatCaches.noindex/macosx14.0-23A334-4a76ee93ef69e462914ffe9883de22b8.sdkstatcache` in compile_command.json
then run `oclint-json-compilation-database` will generate oclint report successfully.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
